name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and deploy with Jekyll Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/srv/jekyll \
            -e JEKYLL_ENV=production \
            jekyll/jekyll:latest \
            /bin/bash -c "chown -R jekyll:jekyll /srv/jekyll && gem install bundler:2.4.22 && bundle install && bundle exec jekyll build"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site